//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace VACuum
{
	class VACResults
	{
		public string DisplayName { get; set; }
		public ulong SteamId { get; set; }
		public bool IsBanned { get; set; }
		
		public VACResults()
		{
			
		}
	}
}

