//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Threading;
using LitJson;
using LeatherLoader;
using System.Text;
using System.Collections;
using System.Reflection;
using UnityEngine;
using uLink;

namespace VACuum
{
	[Bootstrap]
	public class VACuumBootstrap : UnityEngine.MonoBehaviour, INetworkEventHandler
	{
		internal static Queue Results = new Queue();
		public DateTime mNextUpdateCheck = DateTime.MaxValue;
		private NetworkEventHandlerRef mHandler;

		public void Awake()
		{
			DontDestroyOnLoad(this.gameObject);

			mHandler = uLink.Network.RegisterNetworkEventHandler(this);

			mNextUpdateCheck = DateTime.Now;
		}

		private void OnDestroy()
		{
			this.mHandler.Delete ();
		}

		#region INetworkEventHandler implementation

		public void InitializeNetworkEventHandler ()
		{
		}

		public NetworkEventHandlerResponse OnNetworkEvent (string message, object value)
		{
			if (string.Equals (message, "uLink_OnPlayerConnected")) {
				PlayerConnected ((uLink.NetworkPlayer)value);
				return NetworkEventHandlerResponse.Continue;
			} else if (string.Equals (message, "uLink_OnPlayerDisconnected")) {
				PlayerDisconnected ((uLink.NetworkPlayer)value);
				return NetworkEventHandlerResponse.Continue;
			}

			return NetworkEventHandlerResponse.Unhandled;
		}

		public void ShutdownNetworkEventHandler ()
		{
		}

		#endregion
		
		public void PlayerConnected (uLink.NetworkPlayer player)
		{
			SteamConnector user = (SteamConnector)player.localData;
			VACResults result = new VACResults() { DisplayName = user.Login.SteamLogin.UserName, SteamId = user.Login.SteamLogin.SteamID };
			ThreadPool.QueueUserWorkItem((o) =>
			                             {
				//Query result
				string url = string.Format("http://www.vacbans.com/api/?call=profile&comm_id={0}", result.SteamId);
				string response = new System.Net.WebClient().DownloadString(url);
				
				//Parse to json
				JsonData data = JsonMapper.ToObject(response);
				result.IsBanned = (data["vac_ban"].AsInt != 0);
				
				//Place results back to the thread
				lock (Results.SyncRoot)
				{
					Results.Enqueue(result);
				}
			});
		}

		public void PlayerDisconnected(uLink.NetworkPlayer player)
		{
			NetUser user = (NetUser)player.localData;

			ConsoleSystem.Log (user.displayName + " disconnected.");
		}

		public void Update()
		{
			if (DateTime.Now < mNextUpdateCheck)
				return;

			lock (Results.SyncRoot)
			{
				while (Results.Count > 0)
				{
					VACResults result = (VACResults)Results.Dequeue();
					
					StringBuilder builder = new StringBuilder();
					builder.AppendLine(string.Format("VACBans.com tested player {0} with steam ID {1}", result.DisplayName, result.SteamId));
					if (result.IsBanned)
					{
						builder.AppendLine("VACBans.com says player is banned!  Banning...");
						BanList.Add(result.SteamId, result.DisplayName, "Auto-banned by VACuum.");
						BanList.Save();
						NetUser user = NetUser.FindByUserID(result.SteamId);
						
						if (user != null)
							user.Kick(NetError.Facepunch_Kick_Ban, true);
					} else
						builder.AppendLine("VACBans.com says player is A-OK.");
					ConsoleSystem.Log(builder.ToString());
				}
			}
			
			mNextUpdateCheck = DateTime.Now.AddSeconds(5);
		}
	}
}

